### PR TITLE
Website Revamp

### PR DESCRIPTION
**Pull request by riverma**
## Purpose
- A complete revamp of the website using Docusaurus to support the following key goals: 
  - Faceted search of best practices, with a registry of best practice guide metadata as the source to populate the faceted search
  - Folders for each best practice guide, to support misc. files in addition to a write-up
  - Use Docusaurus instead of RETYPE given the latter's free license page limitations
  - Easier way for people to contribute best practices
## Proposed Changes
- [ADD] Docusaurus framework
- [CHANGE] Migrated _all_ existing guides in current website to new framework
- [DELETE] Old GH workflows for RETYPE and markmap generation
## Issues
- #5 
- #21 
- #80 
- #90
## Testing
- Locally built and tested
- Live demo deployed at: https://riverma.github.io/slim/

### CODE REVIEW

**Comment by riverma** [comment]
NOTE: The guides themselves need some work to be made more consistent, since different templates and organizational structures are being used. I propose another PR to address the written material specifically. This ticket is about website framework migration.

**Comment by riverma** [comment]
Feedback from @stirlingalgermissen:
- Dark mode seems broken
- Having the sidebar in the guides be expanded by default (to the first level) would be more informative
- Contributing guide is pretty lengthy / complex. Can it be reorganized?
- About page has lots of content useful for the front page of the website

**Comment by jeffreypon** [comment]
Clicking on any actual "view" button of a guide on the search feature points to a broken link. I know the guides do exist because they appear in the side bar, but the URL path on the "view" button is different from the guides on the side bar. I think the URL from the "view" button is missing "/slim/" at the base of the URL

**Comment by riverma** [comment]
Changes made based on @stirlingalgermissen and @jeffreypon feedback.

See demo: https://riverma.github.io/slim/

**Review by jpl-jengelke — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
