### PR TITLE
Issue #81: Fix for malformed HTML. ...

### PR DESCRIPTION
**Pull request by jpl-jengelke**
## Purpose
- Fix for deprecated/obsolete `center` alignment specs in the README templates
## Proposed Changes
- Fix attributes `align="center"` to explicitly specify style on the elements 
## Issues
- #81 
## Testing
- Document appears to render as expected

### CODE REVIEW

**Review by riverma — CHANGES_REQUESTED** [review]
Hi @jpl-jengelke - thanks for this pull request, but I don't think these new tags would work as intended? Notice how the text is no longer centered.

Your PR [rendered](https://github.com/NASA-AMMOS/slim/blob/d8601c1d9af4e5448f05f0564a8e37a6b311b796/documentation/starter-kits/READMEs/README-sw-proj-template.md):
Screen Shot 2022-12-05 at 3 07 23 PM

The original [rendered](https://github.com/NASA-AMMOS/slim/blob/main/documentation/starter-kits/READMEs/README-sw-proj-template.md):
Screen Shot 2022-12-05 at 3 07 11 PM

**Comment by jpl-jengelke** [comment]
I see. It worked in Chrome. Let's not close this yet. I'll de-prioritize it and follow up with a fix after completing some other tasks. There are other options to fix this more universally.

**Comment by jpl-jengelke** [comment]
This is no longer applicable to the redesigned site. Closing.

**Comment by jpl-jengelke** [comment]
Please keep open. Will revisit shortly.

**Comment by ingyhere** [comment]
The format of the repository has evolved past it. Closing this as no longer needed.

**Pull request closed without merging**
